name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6

      - name: Cypress Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome Report
          path: cypress/reports/html

     # - name: Slack Notification
     #   if: always()
     #   #uses: rtCamp/action-slack-notify@v2
     #   uses: ravsamhq/notify-slack-action@2.5.0
     #   with:
     #     status: ${{ job.status }}
     #     notify_when: 'failure'
     #     notification_title: '{workflow} has {status_message}'
     #     message_format: '{emoji} *{workflow}* {status_message} in this repo https://github.com/RAJ171996/CypressAutomation/actions/runs/${{github.run_id}}'
          
        #env:
          #SLACK_ICON: https://github.com/rtCamp.png?size=48
          #SLACK_MESSAGE: 'Test Automation Reports https://github.com/RAJ171996/CypressAutomation/actions/runs/${{github.run_id}}'
          #SLACK_TITLE: Cypress Web Test

      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status == 'success' && 'passed' || 'failed' }}
          SLACK_TITLE: Cypress Testing against MR
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: ${{ job.status == 'success' && '✅ Cypress tests passed !' || '❌ Cypress tests failed. Please check the build for more details.'  }} https://github.com/RAJ171996/CypressAutomation/actions/runs/${{github.run_id}}
          SLACK_WEBHOOK: ${{ secrets.NEW_WEBHOOK }}

      