name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6

      - name: Cypress Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome Report
          path: cypress/reports/html/ # or path/to/artifact

      #- name: Slack Notification
        #if: always()
        #uses: rtCamp/action-slack-notify@v2
        #env:
          #SLACK_ICON: https://github.com/rtCamp.png?size=48
          #SLACK_MESSAGE: 'Test Automation Reports https://github.com/RAJ171996/CypressAutomation/actions/runs/${{github.run_id}}'
          #SLACK_TITLE: Cypress Web Test
          #SLACK_WEBHOOK: ${{ secrets.NEW_WEBHOOK }}

      - name: Send Slack notification on failure
        if: failure()
        env:
            SLACK_WEBHOOK: ${{ secrets.NEW_WEBHOOK }}
            GITHUB_BRANCH: ${{ github.ref }}
            GITHUB_SHA: ${{ github.sha }}
            GITHUB_ACTOR: ${{ github.actor }}
            GITHUB_REPOSITORY: ${{ github.repository }}
            GITHUB_SERVER_URL: ${{ github.server_url }}
        run: |
            curl -X POST -H 'Content-type: application/json' --data '{
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "❌ Cypress tests failed on branch: *`'"${GITHUB_BRANCH##*/}"'`*"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Commit:* `'"${GITHUB_SHA:0:7}"'`\n*Pushed by:* `$GITHUB_ACTOR`\n*<$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID|View GitHub Actions run>*"
                  }
                }
              ]
            }' $NEW_WEBHOOK    
